name: $(BuildDefinitionName)-$(SourceBranchName)$(Rev:.r)-$(date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
    - develop
    - feature/*

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:

    - task: UseDotNet@2.207.2
      inputs:
        packageType: 'sdk'
        version: '5.x'
        includePreviewVersions: true

    - task: NuGetToolInstaller@1.208.1
      displayName: 'NuGetToolInstaller'
      inputs:
        versionSpec: 4.4.1

    - task: DotNetCoreCLI@2.208.1
      displayName: 'dotnet restore sln'
      inputs:
        command: 'restore'
        projects: 'DevOpsAPI/DevOpsAPI.csproj'
        feedsToUse: 'select'
        vstsFeed: '/5c8e1ed1-e471-485a-86ef-195cb54ec214'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'funkysi1701'
        scannerMode: 'MSBuild'
        projectKey: 'DevOpsAPI'
        projectName: 'DevOpsAPI'
        projectVersion: '$(Build.BuildId)'

    - task: DotNetCoreCLI@2.208.1
      displayName: 'Publishing DevOpsAPI App'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'DevOpsAPI/DevOpsAPI.csproj'
        arguments: '--no-restore --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x64 /p:SourceRevisionId=$(Build.SourceVersion)'        

    - task: PublishBuildArtifacts@1.200.0
      displayName: 'Publish DevOpsAPI'
      inputs:
        PathtoPublish: '$(Pipeline.Workspace)/a/DevOpsAPI.zip'
        ArtifactName: DevOpsAPI                   

    - task: SonarCloudAnalyze@1

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'         

    - task: dependency-checker@1
      inputs:
        path: '$(Build.SourcesDirectory)'
        searchRecursive: true
        combineProjects: false
        includePrerelease: false
        useArtifacts: false
        createBadge: false
        createReport: true
        reportPath: '$(Build.ArtifactStagingDirectory)\dependencies.html'
      env:
        SYSTEM_ACCESSTOKEN: $(system.accesstoken)       