name: $(BuildDefinitionName)-$(SourceBranchName)$(Rev:.r)-$(date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
    - develop
    - feature/*

pool: windows

variables:
  buildConfiguration: 'Release'

stages:

- stage: Build
  jobs:

  - job: Build
    steps:

    - task: UseDotNet@2.207.2
      inputs:
        packageType: 'sdk'
        version: '7.x'
        includePreviewVersions: true

    - task: NuGetToolInstaller@1.208.1
      displayName: 'NuGetToolInstaller'
      inputs:
        versionSpec: 4.4.1

    - task: DotNetCoreCLI@2.210.0
      displayName: 'dotnet restore sln'
      inputs:
        command: 'restore'
        projects: 'DevOpsAPI/DevOpsAPI.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2.210.0
      displayName: 'Publishing DevOpsAPI App'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'DevOpsAPI/DevOpsAPI.csproj'
        arguments: '--no-restore --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --runtime win-x64 /p:SourceRevisionId=$(Build.SourceVersion)'        

    - task: PublishPipelineArtifact@1
      displayName: 'Publishing UI'
      inputs:
        targetPath: '$(Pipeline.Workspace)/a/DevOpsAPI.zip'
        artifact: 'DevOpsAPI'
        publishLocation: 'pipeline'

- stage: DevDeploy
  dependsOn: Build
  jobs:

  - deployment: Deploy
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'devops.funkysi1701.com'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\sites\devops.funkysi1701.com'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              CreateOrUpdateAppPoolForWebsite: true
              ConfigureAuthenticationForWebsite: true
              AppPoolNameForWebsite: 'devops.funkysi1701.com'
              DotNetVersionForWebsite: 'No Managed Code'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
              AnonymousAuthenticationForWebsite: true
              WindowsAuthenticationForWebsite: false

          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'devops.funkysi1701.com'
              Package: 'C:\agent2\_work\1\DevOpsAPI\DevOpsAPI.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true
              JSONFiles: 'appsettings.json'